bylog/views/comment_views.py
from datetime import datetime

from flask import Blueprint, url_for, request, g, flash
from werkzeug.utils import redirect

from bylog import db
from bylog.models import Diary,Comment
from bylog.forms import CommentForm

from bylog.views.auth_views import login_required


bp = Blueprint('comment', __name__, url_prefix='/comment')


@bp.route('/create/<int:diary_id>', methods=('POST',))
@login_required
def create(diary_id):
    form = CommentForm()
    if form.validate_on_submit():
        diary = Diary.query.get_or_404(diary_id)
        content = request.form['content']
        comment = Comment(content=content, create_date=datetime.now(),user_id=g.user.id,user_name=g.user.username)
        diary.comment_set.append(comment)
        db.session.commit()
    else:
        flash('내용을 입력하세요!')
    return redirect(url_for('diary.detail', diary_id=diary_id,form=form))

@bp.route('/delete/<int:comment_id>')
@login_required
def delete(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    diary_id = comment.diary.id
    if g.user == comment.user or g.user.id == 1:
        db.session.delete(comment)
        db.session.commit()
        return redirect(url_for('diary.detail', diary_id=diary_id))
    else:
        flash('삭제권한이 없습니다')

bylog/views/diary_views.py
from flask import Blueprint, render_template, request, url_for, g, flash
from werkzeug.utils import redirect
from datetime import datetime

from .. import db
from bylog.models import Diary, Comment, User
from bylog.forms import DiaryForm,CommentForm

from bylog.views.auth_views import login_required


bp = Blueprint('diary', __name__, url_prefix='/diary')

@bp.route('/create/<int:user_id>', methods=('GET','POST'))
@login_required
def create(user_id):
    form = DiaryForm()
    user = User.query.get(user_id)
    if request.method == 'POST' and form.validate_on_submit():
        diary = Diary(subject=form.subject.data, content=form.content.data, create_date=datetime.now(), user_id=user_id, private = form.private.data )
        db.session.add(diary)
        db.session.commit()
        return redirect(url_for('main.index'))
    return render_template('diary/diary_form.html', form=form,user=user) 

@bp.route('/detail/<int:diary_id>/')
@login_required
def detail(diary_id):
    form = CommentForm()
    diary = Diary.query.get_or_404(diary_id)
    user = User.query.get(diary.user_id)
    return render_template('diary/diary_detail.html', diary=diary,user=user,form=form) 

@bp.route('/modify/<int:diary_id>/', methods=("GET","POST"))
@login_required
def modify(diary_id):
    diary = Diary.query.get_or_404(diary_id)
    user = g.user
    if user != diary.user:
        flash('수정권한이 없습니다')
        return redirect(url_for('diary.detail', diary_id=diary_id))
    if request.method == 'POST':
        form = DiaryForm()
        if form.validate_on_submit():
            form.populate_obj(diary)
            diary.modify_date = datetime.now()
            db.session.commit()
            return redirect(url_for('diary.detail', diary_id=diary_id))
    else:
        form = DiaryForm(obj=diary)
        print(diary.content)
    return render_template('diary/diary_form.html', form=form, user=user) 

@bp.route('/delete/<int:diary_id>')
@login_required
def delete(diary_id):
    diary = Diary.query.get_or_404(diary_id)
    if g.user == diary.user or g.user.id == 1:
        db.session.delete(diary)
        db.session.commit()
        return redirect(url_for('main.bylog',id=diary.user_id))
    else:
        flash('삭제권한이 없습니다')
        return redirect(url_for('diary.detail', diary_id=diary_id))

bylog/templates/diary/diary_detail.html
{%extends 'base2.html'%}

{%block content%}
<div class="diary_detail_content_container">
    <div class="diary_detail_subject"> 
        <h1>{{ diary.subject }}</h1>
        <div class="diary_detail_date_container">
            <div>작성일시 : {{ diary.create_date|datetime }}</div>
            {%if diary.modify_date %}
            <div>수정일시 : {{ diary.modify_date|datetime }}</div>
            {%endif%}
        </div>
    </div>
    <div class="diary_detail_btn_container">
        {%if g.user == diary.user or g.user.id == 1%}
        <span><a href="{{url_for('diary.modify',diary_id=diary.id)}}">수정</a></span>
        <span><a class='delete' data-uri="{{url_for('diary.delete',diary_id=diary.id)}}">삭제</a></span>
        {%endif%}
    </div>
    <div class="diary_detail_content">
        {{ diary.content|markdown }}
    </div>
    <div class="comment_create_form_container">
        {%include 'form_errors.html'%}
        <form class="comment_create_form" action="{{ url_for('comment.create', diary_id=diary.id) }}" method="post">
            {{ form.csrf_token }}
            <textarea name="content" id="comment_content" rows="5"></textarea>
            <input class="comment_btn" type="submit" value="댓글등록">
        </form>
    </div>
</div>

<div class="comment_list_container">
    <h2>{{ diary.comment_set|length }}개의 댓글이 있습니다.</h2>
    <div class="comment_content_list">
        <ul>
        {% for comment in diary.comment_set %}
            <li class="comment_content">
                <div>
                    {{comment.user_name}}
                    
                    {{ comment.create_date|datetime }}

                    {%if g.user == diary.user or g.user.id == 1 or g.user.id == comment.user_id%}
                    <span><a class='delete' data-uri="{{url_for('comment.delete',comment_id=comment.id)}}">삭제</a></span>
                    {%endif%}
                </div>
                <br/>
                {{ comment.content }}
                
            </li>
        {% endfor %}
        </ul>
    </div>
</div>

{%endblock%}


{%block script%}
<script type="text/javascript">
const delete_elements = document.getElementsByClassName("delete");
Array.from(delete_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});
</script>
{%endblock%}

bylog/templates/diary/diary_form.html
{%extends 'base2.html'%}
{%block content%}
    <div class="papaform">
        <h1 class="diaryform_h1">Development Diary</h1>
        <div class="container_diaryform">
            <form method="post" class="diary_form">
                {{ form.csrf_token }}
                {%include 'form_errors.html'%}
                <div>
                    <label for="subject">제목</label>
                    <input type="text" name="subject" id="subject" value="{{form.subject.data or ''}}">
                </div>
                <div>공개여부
                    <select name="private" id="private">
                        <option value="공개">공개</option>
                        <option value="비공개">비공개</option>
                    </select>
                </div>
                <div>
                    <label for="content"></label>
                    <textarea name="content" id="diary_content" rows="30">{{form.content.data or ''}}</textarea>
                </div>
                <div class="diary_submit_">    
                <button class="diary_submit_btn" type="submit">등록하기</button>
                </div>
            </form>
        </div>
    </div>
{%endblock%}

bylog/templates/diary/diary_list.html
{% extends 'base.html' %}
{% block content %}
<div class="board">
    <h1 class="board_h1">
    {%if user.id == session['user_id']%}
        <span class="empty"></span>
    {%endif%}
        <span class="h1_">Development Diary</span>
    {%if user.id == session['user_id']%}
        <span class="plus"><a href="{{ url_for('diary.create') }}"> + </a></span>
    {%endif%}
    </h1>
    {%if diary%}
    <ul>
        {%for diary_list in diary%}
        <li><a href="{{url_for('diary.detail', diary_id = diary_list.id)}}">{{diary_list.subject}}</a></li>
        {%endfor%}
    </ul>
    {%endif%}
</div>
{% endblock %}