bylog/views/diary_views.py
from flask import Blueprint, render_template, request, url_for, g, flash
from werkzeug.utils import redirect
from datetime import datetime

from .. import db
from bylog.models import Diary, Comment, User
from bylog.forms import DiaryForm,CommentForm

from bylog.views.auth_views import login_required


bp = Blueprint('diary', __name__, url_prefix='/diary')

@bp.route('/create/<int:user_id>', methods=('GET','POST'))
@login_required
def create(user_id):
    form = DiaryForm()
    user = User.query.get(user_id)
    if request.method == 'POST' and form.validate_on_submit():
        diary = Diary(subject=form.subject.data, content=form.content.data, create_date=datetime.now(), user_id=user_id, private = form.private.data )
        db.session.add(diary)
        db.session.commit()
        return redirect(url_for('main.index'))
    return render_template('diary/diary_form.html', form=form,user=user) 

@bp.route('/detail/<int:diary_id>/')
@login_required
def detail(diary_id):
    form = CommentForm()
    diary = Diary.query.get_or_404(diary_id)
    user = User.query.get(diary.user_id)
    return render_template('diary/diary_detail.html', diary=diary,user=user,form=form) 

@bp.route('/modify/<int:diary_id>/', methods=("GET","POST"))
@login_required
def modify(diary_id):
    diary = Diary.query.get_or_404(diary_id)
    user = g.user
    if user != diary.user:
        flash('수정권한이 없습니다')
        return redirect(url_for('diary.detail', diary_id=diary_id))
    if request.method == 'POST':
        form = DiaryForm()
        if form.validate_on_submit():
            form.populate_obj(diary)
            diary.modify_date = datetime.now()
            db.session.commit()
            return redirect(url_for('diary.detail', diary_id=diary_id))
    else:
        form = DiaryForm(obj=diary)
        print(diary.content)
    return render_template('diary/diary_form.html', form=form, user=user) 

@bp.route('/delete/<int:diary_id>')
@login_required
def delete(diary_id):
    diary = Diary.query.get_or_404(diary_id)
    if g.user == diary.user or g.user.id == 1:
        db.session.delete(diary)
        db.session.commit()
        return redirect(url_for('main.bylog',id=diary.user_id))
    else:
        flash('삭제권한이 없습니다')
        return redirect(url_for('diary.detail', diary_id=diary_id))

bylog/views/main_views.py
from flask import Blueprint, render_template, url_for, session, request, g, flash, make_response
from werkzeug.utils import redirect
from bylog.models import User, Diary, Guest_book
from bylog import db
from datetime import datetime
from bylog.forms import Guest_bookForm, BlogForm
from bylog.views.auth_views import login_required

bp = Blueprint('main', __name__, url_prefix='/')
    
@bp.route('/')
def index():
    if 'user_id' in session:
        id = session['user_id']
        return redirect(url_for('main.bylog', id=id))
    else :
        return redirect(url_for('auth.login'))

@bp.route('/bylog/<int:id>',methods=("GET","POST"))
@login_required
def bylog(id):
    form = Guest_bookForm()
    page = request.args.get('page', type=int, default=1)
    kw = request.args.get('kw', type=str, default='')
    user = User.query.get(id)
    diary = Diary.query.filter_by(user_id = id).order_by(Diary.create_date.desc())
    guest = Guest_book.query.filter_by(blog=id).order_by(Guest_book.create_date.desc())
    blogcode = user.private_key
    
    if kw:
        search = '%%{}%%'.format(kw)
        diary = db.session.query(Diary).filter(Diary.subject.ilike(search) | 
                    Diary.content.ilike(search)
                ).order_by(Diary.create_date.desc())
    
    diary = diary.paginate(page=page, per_page=10)

    if request.method == 'POST' and form.validate_on_submit():
        guestbook = Guest_book(content=form.content.data, create_date=datetime.now(), user_id=g.user.id,user_name=g.user.username, blog=id)
        db.session.add(guestbook)
        db.session.commit()

    try:
        if id == session['user_id'] or session['user_id'] == 1 or session['code'] == blogcode:
            return render_template('main/base.html',user=user,diary=diary,kw=kw,form=form,guest=guest,id=id )
        elif 'user_id' in session:
            return redirect(url_for('main.bylog', id=session['user_id']))
    except:
        if 'user_id' not in session:
            return redirect(url_for('main.index'))
    return redirect(url_for('main.index'))
        
#리팩토링
# @bp.route('/bylog/<int:id>')
# def bylog(id):
#     user = User.query.get(id)
#     try:
#         if id == session['user_id'] or session['user_id'] == 1:
#             return render_template('main/base.html',user=user)
#         elif session['user_id]:
#             return redirect(url_for('main.bylog', id=session['user_id']))
#     except:
#         return redirect(url_for('main.index'))

@bp.route('/delete/<int:guest_id>')
@login_required
def delete(guest_id):
    guest = Guest_book.query.get_or_404(guest_id)
    if g.user.id == guest.blog or g.user.id == 1 or g.user.id == guest.user_id:        
        db.session.delete(guest)
        db.session.commit()
        return redirect(url_for('main.bylog',id=guest.blog))
    else:
        flash('삭제권한이 없습니다')
        return redirect(url_for('main.bylog', id=guest.blog))
    
@bp.route('/redirecting/<int:id>', methods=("GET","POST"))
@login_required
def redirecting(id):
    user = User.query.get(id)
    form = BlogForm()
    if request.method == 'POST':
        try:
            if form.validate_on_submit():
                code = form.blog.data
                master = User.query.filter_by(private_key = code).first()
                session['code'] = code
                return redirect(url_for('main.bylog', id = master.id))
        except:
            return render_template('main/redirecting.html',user=user, form=form)
    else:
        return render_template('main/redirecting.html',user=user, form=form)
    return render_template('main/redirecting.html',user=user, form=form)

bylog/templates/main/base.html
{%extends 'base2.html'%}
{%block content%}

        <div class="board">

            <!-- Development Diary -->
            <h1 class="board_h1">
                <span class="empty"></span>
                <span class="h1_">Development Diary</span>
            {%if user.id == session['user_id']%}
                <span class="plus"><a href="{{ url_for('diary.create', user_id=user.id) }}"> + </a></span>
            {%else%}
                <span class="empty"></span>
            {%endif%}
            </h1>

            <!-- 게시글 목록 -->
            <div class="boardlist">
                <table class="diary_table">
                    {%if diary.total > 0%}
                        <tr class="table_top">
                            <th class="empty_span"> <!--네이버 카페랑 비슷하게 디자인--></th>
                            <th>제목</th>
                            <th class="diary_create_date">작성일시</th>
                        </tr>
                    {%for diary_list in diary.items%}
                    {%if diary_list.private=='공개'%}
                        <tr class="each_diary">
                            <td class="diary_number">
                                {{ diary.total - ((diary.page-1) * diary.per_page) - loop.index0 }}
                            </td>
                            
                            <td class="diary_subject">
                                <a href="{{url_for('diary.detail', diary_id = diary_list.id)}}">
                                    {{diary_list.subject}}
                                </a>
                                {%if diary_list.comment_set|length > 0%}
                                <span class="commentNumber">[{{diary_list.comment_set|length}}]</span>
                                {%endif%}
                            </td>
                            
                            <td class="diary_date">
                                {{ diary_list.create_date|date }}
                            </td>
                        </tr>
                    {%else%}
                        {%if user.id == session['user_id']%}
                            <tr class="each_diary">
                                <td class="diary_number">
                                    {{ diary.total - ((diary.page-1) * diary.per_page) - loop.index0 }}
                                </td>
                                
                                <td class="diary_subject">
                                    <a href="{{url_for('diary.detail', diary_id = diary_list.id)}}">
                                        {{diary_list.subject}}
                                    </a>
                                    {%if diary_list.comment_set|length > 0%}
                                    <span class="commentNumber">[{{diary_list.comment_set|length}}]</span>
                                    {%endif%}
                                </td>
                                
                                <td class="diary_date">
                                    {{ diary_list.create_date|date }}
                                </td>
                            </tr>
                        {%endif%}
                    {%endif%}
                    {%endfor%}
                {%else%}
                    <br/>
                    <tr class="each_diary"><td></td><td class="diary_subject">아직 게시글이 없습니다.</td><td></td></tr>
                {%endif%}      
                </table>
            </div>

            <!--페이지처리-->
            <div class="page_box">
                <ul class="paging">
                    {% if diary.has_prev %}
                        <li>
                            <a class="page-link" href="?page={{ diary.prev_num }}">이전</a>
                        </li>
                    {% else %}
                        <li class="disabled">
                            <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">이전</a>
                        </li>
                    {% endif %}

                    {% for page_num in diary.iter_pages() %}
                        {% if page_num %}
                            {% if page_num != diary.page %}
                            <li>
                                <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
                            </li>
                            {% else %}
                            <li aria-current="page">
                                <a class="page-link  current_page" href="javascript:void(0)">{{ page_num }}</a>
                            </li>
                            {% endif %}
                        {% else %}
                            <li class="disabled">
                                <a class="page-link" href="javascript:void(0)">...</a>
                            </li>
                        {% endif %}
                    {% endfor %}
                
                    {% if diary.has_next %}
                        <li>
                            <a class="page-link" href="?page={{ diary.next_num }}">다음</a>
                        </li>
                    {% else %}
                        <li class="disabled">
                            <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">다음</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
            
            <!-- 검색창 -->
            <div class="search">
                <input type="text" id="search_kw" value="{{kw or ''}}" placeholder="제목 또는 내용을 입력하세요"/>
                <button class="btn" type="button" id="btn_search">검색</button>
            </div>
        </div>

        <!--방명록-->
        <div class="visit">
            <h1 class="visit_h1">Guest Book</h1>
            <form method="post" class="visit_form">
                {{ form.csrf_token }}
                {% include 'form_errors.html' %}
                <div class="visit_content">
                    <label for="content"></label>
                    <textarea name="content" id="content" rows="10" placeholder="{{user.username}}의 BYlog에 오신 것을 환영합니다. 방명록을 남겨주세요!"></textarea>
                    <button type="submit" class="visit_btn">등록하기</button>
                </div>    
            </form>
            <div class="scroll_box">
                {%if guest.count()>0%}
                    <ul class="guest_content_list">
                    {%for guest_list in guest%}
                        <li class="guest_content">
                            <span class="guest_name">{{guest_list.user_name}}</span>
                            <span>{{guest_list.create_date|datetime}}</span>
                            {%if g.user.id == id or g.user.id == 1 or g.user.id == guest_list.user_id %}
                                <button class="guest_delete"><a href="{{url_for('main.delete',guest_id=guest_list.id)}}">삭제</a></button>
                            {%endif%}
                            <div>{{guest_list.content}}</div>
                        </li>
                    {%endfor%}
                    </ul>
                {%endif%}
            </div>
        </div>

        <!--검색폼 hidden-->
        <form id="searchForm" method="get">
            <input type="hidden" id="kw" name="kw" value="{{ kw or '' }}">
            <input type="hidden" id="page" name="page" value="{{ page }}">
        </form>
{%endblock%}

{%block script%}
        <!--검색js-->
    <script type='text/javascript'>
        const page_elements = document.getElementsByClassName("page-link");
        Array.from(page_elements).forEach(function(element) {
            element.addEventListener('click', function() {
                document.getElementById('page').value = this.dataset.page;
                document.getElementById('searchForm').submit();
            });
        });
        const btn_search = document.getElementById("btn_search");
        btn_search.addEventListener('click', function() {
            document.getElementById('kw').value = document.getElementById('search_kw').value;
            document.getElementById('page').value = 1;
            document.getElementById('searchForm').submit();
        });
    </script>
{%endblock%}

bylog/templates/main/redirecting.html
{%extends 'base2.html'%}
{%block content%}

<div class="papa">

    <div class="mama">
        
        <form method="post">
            {{form.csrf_token}}
            
            <div class="headline">다른 BYlog 방문하기</div>
            
            {% include 'form_errors.html' %}
            <div class="flex1">
                <input placeholder="블로그코드를 입력하면 해당 블로그로 이동합니다." class="flexop" type="text" name="blog"/>
            </div>
                            
            <div class="flex2">

                <input class="flexop2" type="submit" value="이동하기"/>
                                 
            </div>

        </form>    
    
    </div>      

</div>
{%endblock%}